### ISSUE TITLE
Navigation Pane

### ISSUE THREAD

**Issue by tombotron** [TheRealSharuto/Web-Scheduling-App#13]
Navigation in header not working properly.  Appears to be pulling HTML extension from page in wrong directory

**Comment by tombotron** [comment]
![image](https://github.com/TheRealSharuto/Web-Scheduling-App/assets/164106039/03cddaff-4853-4f43-9cb3-5953f3b06589)

**Comment by TheRealSharuto** [comment]
Navigation is not completely fixed yet, but when logged in the links should work

**Comment by TheRealSharuto** [comment]
Also we have not merged recent changes just yet

**Comment by tombotron** [comment]
Got it.  Just going through the test plan and adding some issues for our Phase II submission.

**Comment by tombotron** [comment]
Changed link to drop extension and navigation successful
